# Generated by Django 2.1.5 on 2019-02-04 16:02

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('doc', models.FileField(upload_to='projects/docs/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('stars', models.ManyToManyField(blank=True, related_name='stars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
