# Generated by Django 2.1.5 on 2019-02-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190204_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
